export const countryDataAttribution = { source: "https://github.com/mledoze/countries", license: "https://opendatacommons.org/licenses/odbl/1-0/" };

export const additionalCountries = [
  {"code":"AFG","korean":"아프가니스탄","english":"Afghanistan","lat":33,"lng":65,"zoom":5},
  {"code":"AGO","korean":"앙골라","english":"Angola","lat":-12.5,"lng":18.5,"zoom":4},
  {"code":"ALB","korean":"알바니아","english":"Albania","lat":41,"lng":20,"zoom":6},
  {"code":"AND","korean":"안도라","english":"Andorra","lat":42.5,"lng":1.5,"zoom":8},
  {"code":"ARM","korean":"아르메니아","english":"Armenia","lat":40,"lng":45,"zoom":6},
  {"code":"ATG","korean":"앤티가 바부다","english":"Antigua and Barbuda","lat":17.05,"lng":-61.8,"zoom":8},
  {"code":"AUT","korean":"오스트리아","english":"Austria","lat":47.33333333,"lng":13.33333333,"zoom":6},
  {"code":"AZE","korean":"아제르바이잔","english":"Azerbaijan","lat":40.5,"lng":47.5,"zoom":6},
  {"code":"BDI","korean":"부룬디","english":"Burundi","lat":-3.5,"lng":30,"zoom":6},
  {"code":"BEN","korean":"베냉","english":"Benin","lat":9.5,"lng":2.25,"zoom":5},
  {"code":"BFA","korean":"부르키나파소","english":"Burkina Faso","lat":13,"lng":-2,"zoom":5},
  {"code":"BGR","korean":"불가리아","english":"Bulgaria","lat":43,"lng":25,"zoom":5},
  {"code":"BHR","korean":"바레인","english":"Bahrain","lat":26,"lng":50.55,"zoom":8},
  {"code":"BHS","korean":"바하마","english":"Bahamas","lat":24.25,"lng":-76,"zoom":6},
  {"code":"BIH","korean":"보스니아 헤르체고비나","english":"Bosnia and Herzegovina","lat":44,"lng":18,"zoom":6},
  {"code":"BLR","korean":"벨라루스","english":"Belarus","lat":53,"lng":28,"zoom":5},
  {"code":"BLZ","korean":"벨리즈","english":"Belize","lat":17.25,"lng":-88.75,"zoom":6},
  {"code":"BOL","korean":"볼리비아","english":"Bolivia","lat":-17,"lng":-65,"zoom":4},
  {"code":"BRB","korean":"바베이도스","english":"Barbados","lat":13.16666666,"lng":-59.53333333,"zoom":8},
  {"code":"BRN","korean":"브루나이","english":"Brunei","lat":4.5,"lng":114.66666666,"zoom":7},
  {"code":"BTN","korean":"부탄","english":"Bhutan","lat":27.5,"lng":90.5,"zoom":6},
  {"code":"BWA","korean":"보츠와나","english":"Botswana","lat":-22,"lng":24,"zoom":5},
  {"code":"CAF","korean":"중앙아프리카 공화국","english":"Central African Republic","lat":7,"lng":21,"zoom":5},
  {"code":"CIV","korean":"코트디부아르","english":"Ivory Coast","lat":8,"lng":-5,"zoom":5},
  {"code":"CMR","korean":"카메룬","english":"Cameroon","lat":6,"lng":12,"zoom":5},
  {"code":"COD","korean":"콩고민주공화국","english":"DR Congo","lat":0,"lng":25,"zoom":4},
  {"code":"COG","korean":"콩고공화국","english":"Congo","lat":-1,"lng":15,"zoom":5},
  {"code":"COL","korean":"콜롬비아","english":"Colombia","lat":4,"lng":-72,"zoom":4},
  {"code":"COM","korean":"코모로","english":"Comoros","lat":-12.16666666,"lng":44.25,"zoom":7},
  {"code":"CPV","korean":"카보베르데","english":"Cape Verde","lat":16,"lng":-24,"zoom":7},
  {"code":"CUB","korean":"쿠바","english":"Cuba","lat":21.5,"lng":-80,"zoom":5},
  {"code":"CYP","korean":"키프로스","english":"Cyprus","lat":35,"lng":33,"zoom":7},
  {"code":"CZE","korean":"체코","english":"Czechia","lat":49.75,"lng":15.5,"zoom":6},
  {"code":"DJI","korean":"지부티","english":"Djibouti","lat":11.5,"lng":43,"zoom":6},
  {"code":"DMA","korean":"도미니카 연방","english":"Dominica","lat":15.41666666,"lng":-61.33333333,"zoom":8},
  {"code":"DNK","korean":"덴마크","english":"Denmark","lat":56,"lng":10,"zoom":6},
  {"code":"DOM","korean":"도미니카 공화국","english":"Dominican Republic","lat":19,"lng":-70.66666666,"zoom":6},
  {"code":"ECU","korean":"에콰도르","english":"Ecuador","lat":-2,"lng":-77.5,"zoom":5},
  {"code":"ERI","korean":"에리트레아","english":"Eritrea","lat":15,"lng":39,"zoom":5},
  {"code":"EST","korean":"에스토니아","english":"Estonia","lat":59,"lng":26,"zoom":6},
  {"code":"FJI","korean":"피지","english":"Fiji","lat":-18,"lng":175,"zoom":6},
  {"code":"FSM","korean":"미크로네시아","english":"Micronesia","lat":6.91666666,"lng":158.25,"zoom":8},
  {"code":"GAB","korean":"가봉","english":"Gabon","lat":-1,"lng":11.75,"zoom":5},
  {"code":"GEO","korean":"조지아","english":"Georgia","lat":42,"lng":43.5,"zoom":6},
  {"code":"GIN","korean":"기니","english":"Guinea","lat":11,"lng":-10,"zoom":5},
  {"code":"GMB","korean":"감비아","english":"Gambia","lat":13.46666666,"lng":-16.56666666,"zoom":6},
  {"code":"GNB","korean":"기니비사우","english":"Guinea-Bissau","lat":12,"lng":-15,"zoom":6},
  {"code":"GNQ","korean":"적도 기니","english":"Equatorial Guinea","lat":2,"lng":10,"zoom":6},
  {"code":"GRC","korean":"그리스","english":"Greece","lat":39,"lng":22,"zoom":5},
  {"code":"GRD","korean":"그레나다","english":"Grenada","lat":12.11666666,"lng":-61.66666666,"zoom":8},
  {"code":"GTM","korean":"과테말라","english":"Guatemala","lat":15.5,"lng":-90.25,"zoom":5},
  {"code":"GUY","korean":"가이아나","english":"Guyana","lat":5,"lng":-59,"zoom":5},
  {"code":"HND","korean":"온두라스","english":"Honduras","lat":15,"lng":-86.5,"zoom":5},
  {"code":"HRV","korean":"크로아티아","english":"Croatia","lat":45.16666666,"lng":15.5,"zoom":6},
  {"code":"HTI","korean":"아이티","english":"Haiti","lat":19,"lng":-72.41666666,"zoom":6},
  {"code":"HUN","korean":"헝가리","english":"Hungary","lat":47,"lng":20,"zoom":6},
  {"code":"IRN","korean":"이란","english":"Iran","lat":32,"lng":53,"zoom":4},
  {"code":"IRQ","korean":"이라크","english":"Iraq","lat":33,"lng":44,"zoom":5},
  {"code":"ISR","korean":"이스라엘","english":"Israel","lat":31.47,"lng":35.13,"zoom":6},
  {"code":"JAM","korean":"자메이카","english":"Jamaica","lat":18.25,"lng":-77.5,"zoom":6},
  {"code":"JOR","korean":"요르단","english":"Jordan","lat":31,"lng":36,"zoom":6},
  {"code":"KGZ","korean":"키르기스스탄","english":"Kyrgyzstan","lat":41,"lng":75,"zoom":5},
  {"code":"KIR","korean":"키리바시","english":"Kiribati","lat":1.41666666,"lng":173,"zoom":8},
  {"code":"KNA","korean":"세인트키츠 네비스","english":"Saint Kitts and Nevis","lat":17.33333333,"lng":-62.75,"zoom":8},
  {"code":"KOR","korean":"한국","english":"South Korea","lat":37,"lng":127.5,"zoom":5},
  {"code":"XKX","korean":"코소보","english":"Kosovo","lat":42.666667,"lng":21.166667,"zoom":6},
  {"code":"KWT","korean":"쿠웨이트","english":"Kuwait","lat":29.5,"lng":45.75,"zoom":6},
  {"code":"LAO","korean":"라오스","english":"Laos","lat":18,"lng":105,"zoom":5},
  {"code":"LBR","korean":"라이베리아","english":"Liberia","lat":6.5,"lng":-9.5,"zoom":5},
  {"code":"LBY","korean":"리비아","english":"Libya","lat":25,"lng":17,"zoom":4},
  {"code":"LCA","korean":"세인트루시아","english":"Saint Lucia","lat":13.88333333,"lng":-60.96666666,"zoom":8},
  {"code":"LIE","korean":"리히텐슈타인","english":"Liechtenstein","lat":47.26666666,"lng":9.53333333,"zoom":8},
  {"code":"LKA","korean":"스리랑카","english":"Sri Lanka","lat":7,"lng":81,"zoom":6},
  {"code":"LSO","korean":"레소토","english":"Lesotho","lat":-29.5,"lng":28.5,"zoom":6},
  {"code":"LTU","korean":"리투아니아","english":"Lithuania","lat":56,"lng":24,"zoom":6},
  {"code":"LUX","korean":"룩셈부르크","english":"Luxembourg","lat":49.75,"lng":6.16666666,"zoom":7},
  {"code":"LVA","korean":"라트비아","english":"Latvia","lat":57,"lng":25,"zoom":6},
  {"code":"MAR","korean":"모로코","english":"Morocco","lat":32,"lng":-5,"zoom":5},
  {"code":"MCO","korean":"모나코","english":"Monaco","lat":43.73333333,"lng":7.4,"zoom":8},
  {"code":"MDA","korean":"몰도바","english":"Moldova","lat":47,"lng":29,"zoom":6},
  {"code":"MDG","korean":"마다가스카르","english":"Madagascar","lat":-20,"lng":47,"zoom":5},
  {"code":"MDV","korean":"몰디브","english":"Maldives","lat":3.25,"lng":73,"zoom":8},
  {"code":"MHL","korean":"마셜 제도","english":"Marshall Islands","lat":9,"lng":168,"zoom":8},
  {"code":"MKD","korean":"북마케도니아","english":"North Macedonia","lat":41.83333333,"lng":22,"zoom":6},
  {"code":"MLI","korean":"말리","english":"Mali","lat":17,"lng":-4,"zoom":4},
  {"code":"MLT","korean":"몰타","english":"Malta","lat":35.83333333,"lng":14.58333333,"zoom":8},
  {"code":"MMR","korean":"미얀마","english":"Myanmar","lat":22,"lng":98,"zoom":5},
  {"code":"MNE","korean":"몬테네그로","english":"Montenegro","lat":42.5,"lng":19.3,"zoom":6},
  {"code":"MOZ","korean":"모잠비크","english":"Mozambique","lat":-18.25,"lng":35,"zoom":5},
  {"code":"MRT","korean":"모리타니","english":"Mauritania","lat":20,"lng":-12,"zoom":4},
  {"code":"MUS","korean":"모리셔스","english":"Mauritius","lat":-20.28333333,"lng":57.55,"zoom":7},
  {"code":"MWI","korean":"말라위","english":"Malawi","lat":-13.5,"lng":34,"zoom":5},
  {"code":"MYS","korean":"말레이시아","english":"Malaysia","lat":2.5,"lng":112.5,"zoom":5},
  {"code":"NAM","korean":"나미비아","english":"Namibia","lat":-22,"lng":17,"zoom":5},
  {"code":"NER","korean":"니제르","english":"Niger","lat":16,"lng":8,"zoom":4},
  {"code":"NIC","korean":"니카라과","english":"Nicaragua","lat":13,"lng":-85,"zoom":5},
  {"code":"NPL","korean":"네팔","english":"Nepal","lat":28,"lng":84,"zoom":5},
  {"code":"NRU","korean":"나우루","english":"Nauru","lat":-0.53333333,"lng":166.91666666,"zoom":8},
  {"code":"OMN","korean":"오만","english":"Oman","lat":21,"lng":57,"zoom":5},
  {"code":"PAN","korean":"파나마","english":"Panama","lat":9,"lng":-80,"zoom":6},
  {"code":"PLW","korean":"팔라우","english":"Palau","lat":7.5,"lng":134.5,"zoom":8},
  {"code":"PNG","korean":"파푸아뉴기니","english":"Papua New Guinea","lat":-6,"lng":147,"zoom":5},
  {"code":"POL","korean":"폴란드","english":"Poland","lat":52,"lng":20,"zoom":5},
  {"code":"PRK","korean":"조선","english":"North Korea","lat":40,"lng":127,"zoom":5},
  {"code":"PRT","korean":"포르투갈","english":"Portugal","lat":39.5,"lng":-8,"zoom":6},
  {"code":"PRY","korean":"파라과이","english":"Paraguay","lat":-23,"lng":-58,"zoom":5},
  {"code":"PSE","korean":"팔레스타인","english":"Palestine","lat":31.9,"lng":35.2,"zoom":7},
  {"code":"ROU","korean":"루마니아","english":"Romania","lat":46,"lng":25,"zoom":5},
  {"code":"RWA","korean":"르완다","english":"Rwanda","lat":-2,"lng":30,"zoom":6},
  {"code":"SEN","korean":"세네갈","english":"Senegal","lat":14,"lng":-14,"zoom":5},
  {"code":"SLB","korean":"솔로몬 제도","english":"Solomon Islands","lat":-8,"lng":159,"zoom":6},
  {"code":"SLE","korean":"시에라리온","english":"Sierra Leone","lat":8.5,"lng":-11.5,"zoom":6},
  {"code":"SLV","korean":"엘살바도르","english":"El Salvador","lat":13.83333333,"lng":-88.91666666,"zoom":6},
  {"code":"SMR","korean":"산마리노","english":"San Marino","lat":43.76666666,"lng":12.41666666,"zoom":8},
  {"code":"SOM","korean":"소말리아","english":"Somalia","lat":10,"lng":49,"zoom":5},
  {"code":"SRB","korean":"세르비아","english":"Serbia","lat":44,"lng":21,"zoom":6},
  {"code":"SSD","korean":"남수단","english":"South Sudan","lat":7,"lng":30,"zoom":5},
  {"code":"STP","korean":"상투메 프린시페","english":"São Tomé and Príncipe","lat":1,"lng":7,"zoom":8},
  {"code":"SUR","korean":"수리남","english":"Suriname","lat":4,"lng":-56,"zoom":5},
  {"code":"SVK","korean":"슬로바키아","english":"Slovakia","lat":48.66666666,"lng":19.5,"zoom":6},
  {"code":"SVN","korean":"슬로베니아","english":"Slovenia","lat":46.11666666,"lng":14.81666666,"zoom":6},
  {"code":"SWZ","korean":"에스와티니","english":"Eswatini","lat":-26.5,"lng":31.5,"zoom":6},
  {"code":"SYC","korean":"세이셸","english":"Seychelles","lat":-4.58333333,"lng":55.66666666,"zoom":8},
  {"code":"SYR","korean":"시리아","english":"Syria","lat":35,"lng":38,"zoom":5},
  {"code":"TCD","korean":"차드","english":"Chad","lat":15,"lng":19,"zoom":4},
  {"code":"TGO","korean":"토고","english":"Togo","lat":8,"lng":1.16666666,"zoom":6},
  {"code":"THA","korean":"태국","english":"Thailand","lat":15,"lng":100,"zoom":5},
  {"code":"TJK","korean":"타지키스탄","english":"Tajikistan","lat":39,"lng":71,"zoom":5},
  {"code":"TKM","korean":"투르크메니스탄","english":"Turkmenistan","lat":40,"lng":60,"zoom":5},
  {"code":"TON","korean":"통가","english":"Tonga","lat":-20,"lng":-175,"zoom":8},
  {"code":"TTO","korean":"트리니다드 토바고","english":"Trinidad and Tobago","lat":11,"lng":-61,"zoom":7},
  {"code":"TUN","korean":"튀니지","english":"Tunisia","lat":34,"lng":9,"zoom":5},
  {"code":"TZA","korean":"탄자니아","english":"Tanzania","lat":-6,"lng":35,"zoom":5},
  {"code":"UGA","korean":"우간다","english":"Uganda","lat":1,"lng":32,"zoom":5},
  {"code":"URY","korean":"우루과이","english":"Uruguay","lat":-33,"lng":-56,"zoom":5},
  {"code":"UZB","korean":"우즈베키스탄","english":"Uzbekistan","lat":41,"lng":64,"zoom":5},
  {"code":"VAT","korean":"바티칸","english":"Vatican City","lat":41.9,"lng":12.45,"zoom":8},
  {"code":"VCT","korean":"세인트빈센트 그레나딘","english":"Saint Vincent and the Grenadines","lat":13.25,"lng":-61.2,"zoom":8},
  {"code":"VEN","korean":"베네수엘라","english":"Venezuela","lat":8,"lng":-66,"zoom":5},
  {"code":"VUT","korean":"바누아투","english":"Vanuatu","lat":-16,"lng":167,"zoom":6},
  {"code":"WSM","korean":"사모아","english":"Samoa","lat":-13.58333333,"lng":-172.33333333,"zoom":7},
  {"code":"YEM","korean":"예멘","english":"Yemen","lat":15,"lng":48,"zoom":5},
  {"code":"ZMB","korean":"잠비아","english":"Zambia","lat":-15,"lng":30,"zoom":5},
  {"code":"ZWE","korean":"짐바브웨","english":"Zimbabwe","lat":-20,"lng":30,"zoom":5},
];
